name: Clo
favicon: null
layout_spectrum: 0.4890385593753308
typography_spectrum: 0.59053
title: 'Clo | The Closet'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#06a3b6'
    - '#ffffff'
    - '#1eabbc'
    - '#95d6de'
    - '#e2f3f5'
  brandStrength: 0.05199111392721534
  lightness: 0.40127743780612946
  saturation: 0.01400101650506258
  rhythmicContrast: 0.391742424108088
purpose: []
